# Build configuration
build = {
  command = "npm run build:ssr"
  commandOrigin = "config"
  environment = ["CI"]  # Wrap CI in quotes for clarity
  publish = "/opt/build/repo/dist/Shamrock/browser"
  publishOrigin = "config"
}

# Plugins configuration
[plugins]

# Plugin 1
[[plugins]]
  inputs = {}
  origin = "ui"
  package = "@netlify/angular-runtime"

# Plugin 2
[[plugins]]
  inputs = {}
  origin = "config"
  package = "@netlify/plugin-angular-universal"